import React, { useState } from 'react'
import { Form, useNavigate } from 'react-router-dom'

import { preview } from '../assets'
import { getRandomPrompt } from '../utils'
import { FormFeild, Loader } from '../components'


const CreatePost = () => {

  const navigate = useNavigate();
  useState[form.setForm] = useState({
    name: '',
    prompt: '',
    photo: '',
  });

  const [generatingImg, setGeneratingImg] = useState(false);
  const [loading, setloading] = useState(false);


  const handleSubmit = () => {

  }

  const handleChange =(e) => {

  }

  const handleSupriseMe = () => {

  }


  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>
          Create
        </h1>
        <p className='mt-2 text-[#666e75] text-[14px] max-w[500px] '>
          Create Imaginative and visually stunning images generated by DALL-E AI.
        </p>
      </div>

      <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
        <div className='flex flex-5 gap-5'>
            <FormFeild 
              LabelName = "Your Name"
              type = "text"
              name = "name"
              placeholder = "Ubunye Mweli"
              value = {form.name}
              handleChange = {handleChange}
            />
            <FormFeild 
              LabelName = "Prompt"
              type = "text"
              name = "Prompt"
              placeholder = "A cat made of ice cream"
              value = {form.prompt}
              handleChange = {handleChange}
              isSupriseMe
              handleSupriseMe = {handleSupriseMe}
            />
        </div>
      </form>

    </section>
  )
}

export default CreatePost