import React, { useState } from 'react'
import { Form, useNavigate } from 'react-router-dom'

import { preview } from '../assets'
import { getRandomPrompt } from '../utils'
import { FormFeild, Loader } from '../components'


const CreatePost = () => {

  const navigate = useNavigate();
  const [Form,setForm] = useState({
    name: '',
    prompt: '',
    photo: '',
  });

  const [generatingImg, setGeneratingImg] = useState(false);
  const [loading, setloading] = useState(false);


  const generateImg = () => {

  }

  const handleSubmit = () => {

  }

  const handleChange = (e) => {
     setForm({...Form, [e.target.name]: e.target.value})
  }

  const handleSupriseMe = () => {
    const randomPrompt = getRandomPrompt(Form.prompt);
    setForm({...Form, prompt: randomPrompt})
  }


  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>
          Create
        </h1>
        <p className='mt-2 text-[#666e75] text-[14px] max-w[500px] '>
          Create Imaginative and visually   stunning images generated by DALL-E AI.
        </p>
      </div>

      <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>
          <FormFeild
            LabelName="Your Name"
            type="text"
            name="name"
            placeholder="Ubunye Mweli"
            value={Form.name}
            handleChange={handleChange}
          />
          <FormFeild
            LabelName="Prompt"
            type="text"
            name="Prompt"
            placeholder="A cat sitting on a couch"
            value={Form.prompt}
            handleChange={handleChange}
            isSupriseMe
            handleSupriseMe={handleSupriseMe}
          />
          <div className='relative bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-64 p-3 h-64 flex justify-center items-center'>
            {Form.photo ? (
              <img
                src={Form.photo}
                alt={Form.prompt}
                className='w-full h-full object-contain '
              />
            ) :
              (
                <img
                  src={preview}
                  alt='preview'
                  className='w-9/12 h-9/12 object-contain opacity-40'
                />
              )
            }

            {generatingImg && (
              <div className='absolute inset-0 z-0 flex justify-center items-center bg-[rgba(0,0,0,0.5)] rounded-lg'>
                <Loader />
              </div>
            )}

          </div>
        </div>

        <div className='mt-5 flex gap-5'>
            <button
              type = 'button'
              onClick ={generateImg}
              className='text-white bg-green-700 font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center'
            >
               {generatingImg ? 'Generating ...' : 'Generate'}
            </button>
        </div>

        <div className='mt-10'>
          <p className='mt-2 text-[#666e75] text-[14px]' >
            Once You've Created the image you want you can share it with others in the community.
          </p>
          <button
            type='submit'
            className='mt-3 text-white bg-[#6469ff] font-medium
            rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center'
          >
            {loading ? 'Sharing...' : "Share withthe community"}
          </button>
        </div>
      </form>
    </section>
  )
}

export default CreatePost